### ISSUE TITLE
Device to Netbox, issue create netbox device  platform.id, object has no attribute 'id

### ISSUE THREAD

**Issue by abdikanipd** [falz/netbox-device-scripts#1]
Hello @falz  device to netbox python i get this issue .....
 
Password for user "user" to log in to "X.x.x.x": 
Connection summary:

        user:   Netbox
        device: X,x,x,x
        model:  cisco
        os:     ios
        role:   router
        site:   eid1
        tenant: tname

Netbox sanity checks: Done
Connecting to Xx.x.x.: Done
Getting info: Facts Interfaces IPs BGP Done

Creating netbox device: Traceback (most recent call last):
  File "c:\Users\abdik\Documents\Visual Code\Netbox\Device_Scripts\device-to-netbpx.py", line 514, in <module>
    device_result = create_netbox_device(config, nb, args, device_dict, sanitydata)
  File "c:\Users\abdik\Documents\Visual Code\Netbox\Device_Scripts\device-to-netbpx.py", **line 240, in create_netbox_device        
    platform =  platform.id,**
**AttributeError: 'NoneType' object has no attribute 'id'**	

Please help to resolve this issue.

**Comment by falz** [comment]
Do you have a platform set on your netbox device? it has to be set and match a NAPALM platform, which is IOS in your case. 

https://docs.netbox.dev/en/stable/models/dcim/platform/

**Comment by abdikanipd** [comment]
Yes there is platform in netbox and have NAPALM iso,  still there is issue **"Model c3750e-universalk9-m doesn't exist!"** 
this platform model is existing my netbox, as id of dcim.platform:3 (c3750e-universalk9-m) id: c3750e-universalk9-m

-d X.x.x.x -s EID -t TL -m c3750e-universalk9-m -r cisco -u Username.
![Uploading platform.png…]()

**Comment by falz** [comment]
What version of Netbox are you using? I've just committed a change https://github.com/falz/netbox-device-scripts/commit/fcbab2fa25c309b0d3916dccebb8e7dd6543a4f1 that removes the now deprecated slugs, which may or may not help. I'm testing on 3.2.5.

**Comment by abdikanipd** [comment]
Model c3750e-universalk9-m doesn't exist! still this issue is existing,  Netbox (v3.2.5) Model is platform in this version.

**Comment by falz** [comment]
In your browser, does this URL work? It should return JSON. It should be the same query that this code does to find that model.

/api/dcim/device-types/?model__ie=c3750e-universalk9-m

**Comment by abdikanipd** [comment]
@falz  thanks finally get the issue and the point.

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 2,
            "url": "http://"Hostname".isp.com/api/dcim/device-types/2/?format=api",
            "display": "Catalyst 3750X-48P-S",
            "manufacturer": {
                "id": 2,
                "url": "http://nodea.isp.com/api/dcim/manufacturers/2/?format=api",
                "display": "CISCO",
                "name": "CISCO",
                "slug": "cisco"
            },
            **"model": "Catalyst 3750X-48P-S",**
            "slug": "catalyst-3750x-48p-s",
            "part_number": "WS-C3750X-48P-S",
            "u_height": 1,
            "is_full_depth": false,
            "subdevice_role": null,
            "airflow": {
                "value": "front-to-rear",
                "label": "Front to rear"
            },
            "front_image": "http://nodea.isp.com/media/devicetype-images/Switch-3750-X-48P-S.jpg",
            "rear_image": "http://nodea.isp.com/media/devicetype-images/switches-ws-c3750x-48p-s-ws-c3750x-48p-s-rear.jpg",
            "comments": "",
            "tags": [],
            "custom_fields": {},
            "created": "2022-06-28T08:10:37.347778+03:00",
            "last_updated": "2022-06-28T11:37:11.610326+03:00",
            "device_count": 0
        }
    ]
}
Solution use model: "Catalyst 3750X-48P-S" name instead  of using "slug": "catalyst-3750x-48p-s".
